### ISSUE TITLE
Making the images in the front page parallax shorter

### ISSUE THREAD

**Issue by grappler** [WPSwitzerland/wordcampbern2017#1]
Could you make the images in the front page shorter please? It should work with this CSS.

```css
@media screen and (min-width: 48em) {
.panel-image {
    height: 17.5rem;
}
}
```
