### ISSUE TITLE
Style requests

### ISSUE THREAD

**Issue by stebrech** [WPSwitzerland/wordcampbern2017#2]
- [x] I recommend use the colours defined in the CD (Aare green #50afa0 for headings / Grey #495057 for general text and headings in the footer)
- [x] I would delete `font size: 1rem` at the media querry `(min-width: 48em)`. Because of the one col layout, `1.125rem` works better for me. This would need to be changed for `body, …` as well as for `.main-navigation`.
- [x] Suggestion for the header image:
```css
.custom-header-media:before {
background: -moz-radial-gradient(center, ellipse cover, rgba(250,252,250,1) 0%, rgba(80,175,160,0.8) 100%); /* FF3.6-15 */
background: -webkit-radial-gradient(center, ellipse cover, rgba(250,252,250,1) 0%,rgba(80,175,160,0.8) 100%); /* Chrome10-25,Safari5.1-6 */
background: radial-gradient(ellipse at center, rgba(250,252,250,1) 0%,rgba(80,175,160,0.8) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fafcfa', endColorstr='#cc50afa0',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
background-size: 100% 200%;
background-position: center;
}
.has-header-image .custom-header-media img, .has-header-video .custom-header-media video, .has-header-video .custom-header-media iframe, .has-header-image:not(.twentyseventeen-front-page):not(.home) .custom-header-media img {
filter: contrast(2);
}
```
- [x] Bug in the footer social menu
![wordcamp_bern_ _unis_building__8th_9th_september_2017](https://cloud.githubusercontent.com/assets/2923268/24919091/cc2995b2-1ee2-11e7-86b6-5686679f7cea.jpg)
- [x] Everything could be positioned more left-justified on the desktop. The left edge of the text in the main navigation, the main content and the footer are different.
