### ISSUE TITLE
Mobile design: Attendees

### ISSUE THREAD

**Issue by grappler** [WPSwitzerland/wordcampbern2017#3]
The following CSS should be sufficient for the mobile view.

```css
// Mobile
#tix-attendees .tix-columns-3 li {
    width: 100%;
}
// Tablet
#tix-attendees .tix-columns-3 li {
    width: 50%;
}
```
https://2017.bern.wordcamp.org/attendees/
