### ISSUE TITLE
Sponsors design changes

### ISSUE THREAD

**Issue by grappler** [WPSwitzerland/wordcampbern2017#7]
- [x] 1. The micro sponsors design on the [Sponsors page](https://2017.bern.wordcamp.org/sponsors/) needs to adapted.

![image](https://user-images.githubusercontent.com/1785641/27826032-e5a7d6c8-60b1-11e7-8fec-a2f3f862f911.png)

- [x] 2. Could we make the sponsor logos on the [front page](https://2017.bern.wordcamp.org/) about the same height?

![image](https://user-images.githubusercontent.com/1785641/27826088-1e6bc280-60b2-11e7-99b9-c6a1d490e3ed.png)

- [x]  3. As we have only three Gold sponsors could we centre the third sponsor?
![image](https://user-images.githubusercontent.com/1785641/27826128-40af33fe-60b2-11e7-90ef-882cdc42eecc.png)

**Comment by grappler** [comment]
I am not sure if we can do something about the mixed matched background colours of the logos.

**Comment by ocean90** [comment]
You could make the background of the sponsors section white.

```css
.wcorg-sponsors {
	background: #fff;
	box-shadow: -600px 0 0 0 #fff, 600px 0 0 0 #fff; /* left/right overflow */
}
```
